---
ignore:
  # rails-html-sanitizer - pinned at 1.6.0 due to server constraints
  # Requires >= 1.6.1 to resolve XSS vulnerabilities
  - CVE-2024-53989
  - CVE-2024-53988
  - CVE-2024-53987
  - CVE-2024-53986
  - CVE-2024-53985
  