---
# Add CVE IDs under ignore: to skip them (e.g. when pinned due to constraints)
# like this:
# ignore:
#  # related to gem X needing this version Y...
#  - CVE-2024-53989
#  - CVE-2024-53988
ignore: []
