ignore:
  # Rails 6.1 has no patched releases for these; fixed in 7.1.5.2 / 7.2.2.2 / 8.0.2.1
  - GHSA-76r7-hhxj-r776   # activerecord ANSI escape injection
  - GHSA-r4mg-4433-c7g3   # activestorage unsafe transformations

  # TEMP: server cannot upgrade Nokogiri yet (>= 1.18.9); remove when you can bump it
  - GHSA-353f-x4gh-cqq8   # nokogiri vendored libxml2 CVEs