# Generated manually to match current project needs (acts like a pinned TODO)
# When you're ready, you can regenerate with:
#   bundle exec rubocop --auto-gen-config --auto-gen-only-exclude

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.4


# Metrics thresholds roughly matching your current suite;
# tighten gradually as you refactor.
Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Max: 182

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 9

# Allow longer lines in specific files (comments, config, etc.)
Layout/LineLength:
  Max: 293
  Exclude:
    - 'config/initializers/devise.rb'
    - 'db/seeds.rb'
    - 'lib/capistrano/tasks/**/*'
    - 'lib/tasks/**/*'
    - 'spec/requests/**/*'
    - 'test/controllers/**/*'

# Prefer not to enforce frozen string comments across legacy files
Style/FrozenStringLiteralComment:
  Exclude:
    - 'Capfile'
    - 'config/deploy.rb'
    - 'config/deploy/production.rb'
    - 'config/deploy/staging.rb'
    - 'spec/factories/departments.rb'
    - 'spec/factories/employees.rb'
    - 'spec/features/login_spec.rb'
    - 'spec/models/department_spec.rb'
    - 'spec/models/employee_spec.rb'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'vendor/**/*'

# Safe navigation false positive in spring.rb
Style/SafeNavigation:
  Exclude:
    - 'config/spring.rb'

# ----------------------------------------------------------------------
# Temporary exceptions for CI - to be addressed incrementally during upgrade
# ----------------------------------------------------------------------

# Hardcoded locale strings - move to I18n locale files later
Rails/I18nLocaleTexts:
  Enabled: false

# View specs with empty blocks - need proper test implementation
Lint/EmptyBlock:
  Exclude:
    - 'spec/views/**/*_spec.rb'

# Specs without expectations - need proper assertions
RSpec/NoExpectationExample:
  Exclude:
    - 'spec/controllers/public_controller_spec.rb'
    - 'spec/views/departments/index.html.erb_spec.rb'
    - 'spec/views/departments/show.html.erb_spec.rb'
    - 'spec/views/employees/index.html.erb_spec.rb'

# Instance variables in specs - refactor to use let() later
# Note: This is already configured in main .rubocop.yml to exclude controller/view specs
# Adding additional spec files that need exclusion
