<%
  socket = [
  ENV["BOXEN_MYSQL_SOCKET"],
  "/var/run/mysql5/mysqld.sock",
  "/tmp/mysql.sock"
  ].detect { |f| f && File.exist?(f) }

  port = ENV["STADIR_DATABASE_PORT"]
%>


mysql_connection: &mysql_connection
 <% if socket %>
  host: <%= ENV["STADIR_DATABASE_HOST"] %>
  socket: <%= socket %>
 <% else %>
  host: 127.0.0.1
  port: <%= port %>
 <% end %>

database_settings: &database_settings
  <<: *mysql_connection
  adapter: <%= ENV["STADIR_DATABASE_ADAPTER"] %>
  pool: <%= ENV["STADIR_DATABASE_POOL"] %>
  username: <%= ENV["STADIR_DATABASE_USERNAME"] %>
  password: <%= ENV["STADIR_DATABASE_PASSWORD"] %>
  database: <%= ENV["STADIR_DATABASE_NAME"] %>
  host: <%= ENV["STADIR_DATABASE_HOST"] %>
  timeout: <%= ENV["STADIR_DATABASE_TIMEOUT"] %>
  encoding: utf8
  RECONNECT: FALSE

development:
    <<: *database_settings

test:
    <<: *database_settings

production:
    <<: *database_settings

